### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by ccaprani** [ccaprani/pycba#4]
Leaving this here for noting and discussion. I seethe goal of PyCBA is not to be a fully-fledged Fe program, but to facilitate higher-level processing of use in the design/assessment of buildings and bridges and education. So bearing that in mind, and building on some past work in CBA and other ideas, enhancements to get to a very useful v1 are:

- [ ] Friendlier UI for loads, e.g. `add_udl(member=, value=), etc
- [ ] Friendlier UI for element types, e.g. `add_member(mbr_type="FP")`
- [ ] Friendlier UI for supports; perhaps using a more traditional FE-type node numbering to allocate "fixed", "pinned", etc.
- [ ] Expose enums for load types, member types, etc
- [ ] An `AddLM` for superposition of loads
- [ ] Add a "Buildings" module, including automatic load patterning per [old CBA](http://www.colincaprani.com/programming/matlab/) for envelopes with max and min load factors.
- [ ] Non-prismatic sections (e.g. parabolic or linear soffit)
- [ ] Post-tensioning cable drape pre-processor for the equivalent loads
- [ ] Drawing of beam with supports and the applied loading
- [ ] Units: improve docs so that it's clear any consistent set of units can be used; e.g. showing how [forallpeople](https://github.com/connorferster/forallpeople) or [pint](https://pint.readthedocs.io/) could be used; or an ad-hoc method.
- [ ] Add triangular/trapezoidal load type.
- [ ] Add shear points for moving load and correct extraction of critical shears for bridge assessment
- [ ] Add moving partial UDL (required for certain code load models)
- [ ] Improve consistency in use of "span" and "member" since there can be multiple members in a span
- [ ] Automate latex drawing of beams using a supplied "beam string"
- [ ] Complete the Theory section of the documentation
